# -*- coding: utf-8 -*-
"""Copie de traffic sign.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gMACfC-xIF4FHI65pa8nX4G58Rtraa26

https://www.kaggle.com/datasets/pkdarabi/cardetection/data
"""

from google.colab import drive
drive.mount('/content/drive')

# Install dependencies
!pip install torch torchvision pycocotools kaggle -q

# Import libraries
import os
import torch
import torchvision
from torchvision.models.detection import fasterrcnn_resnet50_fpn
from torchvision.transforms import functional as F
from torch.utils.data import DataLoader, Dataset
from PIL import Image
import zipfile
import json

# Upload kaggle.json
from google.colab import files
files.upload()

# Set up Kaggle API credentials
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Download the dataset using Kaggle API
!kaggle datasets download -d pkdarabi/cardetection

# Unzip dataset
with zipfile.ZipFile("cardetection.zip", 'r') as zip_ref:
    zip_ref.extractall("/content/data")

!pip install ultralytics

# Import Essential Libraries
import random
from ultralytics import YOLO
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style='darkgrid')
from tqdm.notebook import trange, tqdm
import warnings
warnings.filterwarnings('ignore')

# Configure the visual appearance of Seaborn plots
sns.set(rc={'axes.facecolor': '#eae8fa'}, style='darkgrid')

Image_dir = '/content/data/car/train/images'

num_samples = 9
image_files = os.listdir(Image_dir)

# Randomly select num_samples images
rand_images = random.sample(image_files, num_samples)

fig, axes = plt.subplots(3, 3, figsize=(11, 11))

for i in range(num_samples):
    image = rand_images[i]
    ax = axes[i // 3, i % 3]
    ax.imshow(plt.imread(os.path.join(Image_dir, image)))
    ax.set_title(f'Image {i+1}')
    ax.axis('off')

plt.tight_layout()
plt.show()

# Build from YAML and transfer weights
Final_model = YOLO('yolov8n.pt')

# Training The Final Model
Result_Final_model = Final_model.train(data="/content/data/car/data.yaml",epochs=100,   # Number of training epochs
    imgsz=640,    # Image size (you can adjust this)
    batch=64,     # Batch size (adjust based on your GPU capabilities)
    device=0 )

"""You run the model from the codes below + pip install ultralytics

from ultralytics import YOLO
from PIL import Image
import matplotlib.pyplot as plt

# Load the trained model
trained_model = YOLO("C:\Users\apple pro\Downloads\best.pt")  # Path to the best weights from training

# Test the model on an image
image_path = '/content/t2.jpg'  # Path to the test image
results = trained_model.predict(source=image_path, save=True, imgsz=640)  # Run prediction

# Display the prediction result
# The result will be saved in the default location: '/content/runs/predict'
result_image_path = results[0].path  # Path of the output image with detections
image = Image.open(result_image_path)

# Plot the result
plt.figure(figsize=(10, 10))
plt.imshow(image)
plt.axis('off')
plt.title("Prediction Results")
plt.show()
"""

!pip install --upgrade ultralytics

from ultralytics import YOLO
from PIL import Image
import matplotlib.pyplot as plt

# Load the trained model
trained_model = YOLO('/content/sample_data/best (1).pt')  # Path to the best weights from training

# Test the model on an image
image_path = '/content/sample_data/speed70.jpg'  # Path to the test image
results = trained_model.predict(source=image_path, save=True, imgsz=640)  # Run prediction

# Display the prediction result
# The result will be saved in the default location: '/content/runs/predict'
result_image_path = results[0].path  # Path of the output image with detections
image = Image.open(result_image_path)

# Plot the result
plt.figure(figsize=(10, 10))
plt.imshow(image)
plt.axis('off')
plt.title("Prediction Results")
plt.show()